-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Latte.

module Latte.PrintLatte where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Latte.AbsLatte

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Latte.AbsLatte.Ident where
  prt _ (Latte.AbsLatte.Ident i) = doc $ showString i
instance Print (Latte.AbsLatte.Program' a) where
  prt i = \case
    Latte.AbsLatte.Prog _ topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print (Latte.AbsLatte.TopDef' a) where
  prt i = \case
    Latte.AbsLatte.FnDef _ type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
    Latte.AbsLatte.ClassDef _ id_ classattrs -> prPrec i 0 (concatD [doc (showString "class"), prt 0 id_, doc (showString "{"), prt 0 classattrs, doc (showString "}")])
    Latte.AbsLatte.ClassDefE _ id_1 id_2 classattrs -> prPrec i 0 (concatD [doc (showString "class"), prt 0 id_1, doc (showString "extends"), prt 0 id_2, doc (showString "{"), prt 0 classattrs, doc (showString "}")])

instance Print (Latte.AbsLatte.ClassAttr' a) where
  prt i = \case
    Latte.AbsLatte.ClassField _ type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString ";")])
    Latte.AbsLatte.ClassMethod _ type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])

instance Print [Latte.AbsLatte.ClassAttr' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [Latte.AbsLatte.TopDef' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Latte.AbsLatte.Arg' a) where
  prt i = \case
    Latte.AbsLatte.Ar _ type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])

instance Print [Latte.AbsLatte.Arg' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Latte.AbsLatte.Block' a) where
  prt i = \case
    Latte.AbsLatte.Blk _ stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [Latte.AbsLatte.Stmt' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Latte.AbsLatte.Stmt' a) where
  prt i = \case
    Latte.AbsLatte.Empty _ -> prPrec i 0 (concatD [doc (showString ";")])
    Latte.AbsLatte.BStmt _ block -> prPrec i 0 (concatD [prt 0 block])
    Latte.AbsLatte.Decl _ type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    Latte.AbsLatte.Ass _ expr1 expr2 -> prPrec i 0 (concatD [prt 6 expr1, doc (showString "="), prt 0 expr2, doc (showString ";")])
    Latte.AbsLatte.Incr _ expr -> prPrec i 0 (concatD [prt 6 expr, doc (showString "++"), doc (showString ";")])
    Latte.AbsLatte.Decr _ expr -> prPrec i 0 (concatD [prt 6 expr, doc (showString "--"), doc (showString ";")])
    Latte.AbsLatte.Ret _ expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    Latte.AbsLatte.VRet _ -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    Latte.AbsLatte.Cond _ expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    Latte.AbsLatte.CondElse _ expr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])
    Latte.AbsLatte.While _ expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    Latte.AbsLatte.ForEach _ type_ id_ expr stmt -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 type_, prt 0 id_, doc (showString ":"), prt 6 expr, doc (showString ")"), prt 0 stmt])
    Latte.AbsLatte.SExp _ expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
    Latte.AbsLatte.SPrintInt _ expr -> prPrec i 0 (concatD [doc (showString "printInt"), doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString ";")])
    Latte.AbsLatte.SPrintStr _ expr -> prPrec i 0 (concatD [doc (showString "printString"), doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString ";")])
    Latte.AbsLatte.Error _ -> prPrec i 0 (concatD [doc (showString "error"), doc (showString "("), doc (showString ")"), doc (showString ";")])

instance Print (Latte.AbsLatte.Item' a) where
  prt i = \case
    Latte.AbsLatte.NoInit _ id_ -> prPrec i 0 (concatD [prt 0 id_])
    Latte.AbsLatte.Init _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr])

instance Print [Latte.AbsLatte.Item' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Latte.AbsLatte.Type' a) where
  prt i = \case
    Latte.AbsLatte.Int _ -> prPrec i 0 (concatD [doc (showString "int")])
    Latte.AbsLatte.Str _ -> prPrec i 0 (concatD [doc (showString "string")])
    Latte.AbsLatte.Bool _ -> prPrec i 0 (concatD [doc (showString "boolean")])
    Latte.AbsLatte.Void _ -> prPrec i 0 (concatD [doc (showString "void")])
    Latte.AbsLatte.ArrT _ type_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "[]")])
    Latte.AbsLatte.ClassT _ id_ -> prPrec i 0 (concatD [prt 0 id_])
    Latte.AbsLatte.Fun _ type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])

instance Print [Latte.AbsLatte.Type' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Latte.AbsLatte.Expr' a) where
  prt i = \case
    Latte.AbsLatte.EVar _ id_ -> prPrec i 6 (concatD [prt 0 id_])
    Latte.AbsLatte.ENull _ -> prPrec i 6 (concatD [doc (showString "null")])
    Latte.AbsLatte.EVarArr _ expr1 expr2 -> prPrec i 6 (concatD [prt 6 expr1, doc (showString "["), prt 0 expr2, doc (showString "]")])
    Latte.AbsLatte.ELitInt _ n -> prPrec i 6 (concatD [prt 0 n])
    Latte.AbsLatte.ELitTrue _ -> prPrec i 6 (concatD [doc (showString "true")])
    Latte.AbsLatte.ELitFalse _ -> prPrec i 6 (concatD [doc (showString "false")])
    Latte.AbsLatte.EApp _ id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    Latte.AbsLatte.EString _ str -> prPrec i 6 (concatD [printString str])
    Latte.AbsLatte.ESelf _ -> prPrec i 6 (concatD [doc (showString "self")])
    Latte.AbsLatte.EArr _ type_ expr -> prPrec i 6 (concatD [doc (showString "new"), prt 0 type_, doc (showString "["), prt 0 expr, doc (showString "]")])
    Latte.AbsLatte.EArrClass _ id_ expr -> prPrec i 6 (concatD [doc (showString "new"), prt 0 id_, doc (showString "["), prt 0 expr, doc (showString "]")])
    Latte.AbsLatte.EClass _ id_ -> prPrec i 6 (concatD [doc (showString "new"), prt 0 id_])
    Latte.AbsLatte.EAttr _ expr id_ -> prPrec i 6 (concatD [prt 6 expr, doc (showString "."), prt 0 id_])
    Latte.AbsLatte.EMethod _ expr id_ exprs -> prPrec i 6 (concatD [prt 6 expr, doc (showString "."), prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    Latte.AbsLatte.Neg _ expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    Latte.AbsLatte.Not _ expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    Latte.AbsLatte.EMul _ expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    Latte.AbsLatte.EAdd _ expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    Latte.AbsLatte.ERel _ expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    Latte.AbsLatte.EAnd _ expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    Latte.AbsLatte.EOr _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
    Latte.AbsLatte.SReadInt _ -> prPrec i 0 (concatD [doc (showString "readInt"), doc (showString "("), doc (showString ")")])
    Latte.AbsLatte.SReadStr _ -> prPrec i 0 (concatD [doc (showString "readString"), doc (showString "("), doc (showString ")")])

instance Print [Latte.AbsLatte.Expr' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Latte.AbsLatte.AddOp' a) where
  prt i = \case
    Latte.AbsLatte.Plus _ -> prPrec i 0 (concatD [doc (showString "+")])
    Latte.AbsLatte.Minus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (Latte.AbsLatte.MulOp' a) where
  prt i = \case
    Latte.AbsLatte.Times _ -> prPrec i 0 (concatD [doc (showString "*")])
    Latte.AbsLatte.Div _ -> prPrec i 0 (concatD [doc (showString "/")])
    Latte.AbsLatte.Mod _ -> prPrec i 0 (concatD [doc (showString "%")])

instance Print (Latte.AbsLatte.RelOp' a) where
  prt i = \case
    Latte.AbsLatte.LTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    Latte.AbsLatte.LE _ -> prPrec i 0 (concatD [doc (showString "<=")])
    Latte.AbsLatte.GTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    Latte.AbsLatte.GE _ -> prPrec i 0 (concatD [doc (showString ">=")])
    Latte.AbsLatte.EQU _ -> prPrec i 0 (concatD [doc (showString "==")])
    Latte.AbsLatte.NE _ -> prPrec i 0 (concatD [doc (showString "!=")])
